# Generated by Django 3.2.7 on 2021-09-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='Rock', max_length=50),
            preserve_default=False,
        ),
    ]
